CREATE TABLE "Ingredientes" (
    Id_Ingrediente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome VARCHAR(80) NOT NULL,
    Ativo BIT NOT NULL
);

CREATE TABLE "Receitas" (
    Id_Receita INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Preparo VARCHAR(10485760) NOT NULL
);

CREATE TABLE "Receita_Ingredientes" (
    Id_Receita_Ingredientes INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Ingrediente INT NOT NULL,
    Id_Receita INT NOT NULL,
    CONSTRAINT fk_Receitas FOREIGN KEY(Id_Receita) REFERENCES "Receitas"(Id_Receita),
    CONSTRAINT fk_Ingredientes FOREIGN KEY(Id_Ingrediente) REFERENCES "Ingredientes"(Id_Ingrediente)
);
