// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Ingredient struct {
	ID       int64     `json:"id"`
	Nome     string    `json:"nome"`
	Ativo    bool      `json:"ativo"`
	CriadoEm time.Time `json:"criado_em"`
}
