// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	AddIngredient(ctx context.Context, arg AddIngredientParams) (Ingredient, error)
	DeleteIngredient(ctx context.Context, id int64) error
	GetIngreditent(ctx context.Context, id int64) (Ingredient, error)
	ListIngredients(ctx context.Context, arg ListIngredientsParams) ([]Ingredient, error)
	UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error)
}

var _ Querier = (*Queries)(nil)
